version: 2
jobs:
  test:
    working_directory: ~/ice
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install coveralls
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Run the Tests
          command: |
            . venv/bin/activate
            py.test ice/tests --junitxml=test-reports/output.xml --cov=ice
            coveralls
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/
  publish:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = __token__" >> ~/.pypirc
            echo -e "password = $PYPI_TOKEN" >> ~/.pypirc
      - run:
          name: Build the package
          command: python3 setup.py sdist bdist_wheel
      - run:
          name: Upload to pypi
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install twine
            python3 -m twine upload dist/*
workflows:
  version: 2
  test-and-publish:
    jobs:
      - test
      - publish:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/